/* Auto-generated by apps/api/scripts/gen_types.py - do not edit. */

export interface AnalysisOut {
  id: number;
  commit_sha: string;
  status: string;
  health_score: number | null;
  metrics: Record<string, unknown>;
  analyzer_version: string;
  cache_hit?: boolean;
}

export interface ApproveIn {
  github_token?: string;
}

export interface DevLoginIn {
  login?: string;
}

export interface EventOut {
  id: number;
  task_id: number | null;
  event_type: string;
  payload: Record<string, unknown>;
  created_at: string;
}

export interface FileOut {
  path: string;
  language: string;
  loc: number;
  complexity: number;
  maintainability: number | null;
  churn: number;
  test_presence: number;
  risk_score: number;
  in_degree: number;
  out_degree: number;
  risk_contributors?: Record<string, number>;
}

export interface FindingOut {
  id: number;
  type: string;
  severity: string;
  path: string;
  line: number | null;
  message: string;
  rule_id: string;
  evidence: Record<string, unknown>;
  priority_score: number;
  guidance?: Record<string, string>;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface HealthOut {
  status: string;
  analyzer_version: string;
  environment: string;
}

export interface MissionIn {
  goal: string;
  finding_id?: number | null;
}

export interface MissionOut {
  id: number;
  repo_id: number;
  goal: string;
  finding_id: number | null;
  status: string;
  plan: Record<string, unknown>;
  result: Record<string, unknown>;
}

export interface PullRequestOut {
  pr_number: number;
  url: string;
  branch: string;
  base: string;
  state: string;
}

export interface RepoIn {
  owner: string;
  name: string;
}

export interface RepoOut {
  id: number;
  owner: string;
  name: string;
  default_branch: string;
  last_analyzed_sha: string | null;
}

export interface ValidationError {
  loc: string | number[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}
