"""Generate TypeScript types from the FastAPI OpenAPI schema.

Usage: python scripts/gen_types.py  (writes packages/shared-types/index.d.ts)
Deterministic; run in CI to detect drift (git diff check).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "packages" / "shared-types" / "index.d.ts"


def ts_type(schema: dict, prefix: str = "") -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    kind = schema.get("type", "any")
    if kind == "array":
        return f"{ts_type(schema.get('items', {}), prefix)}[]"
    if kind == "object":
        props = schema.get("properties", {})
        if not props:
            values = schema.get("additionalProperties")
            if isinstance(values, dict):
                return f"Record<string, {ts_type(values, prefix)}>"
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        lines = ["{"]
        for name, prop in props.items():
            opt = "" if name in required else "?"
            lines.append(f"  {name}{opt}: {ts_type(prop, prefix)};")
        lines.append("}")
        return "\n".join(lines)
    if kind == "string":
        if "enum" in schema:
            return " | ".join(json.dumps(v) for v in schema["enum"])
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if isinstance(schema.get("anyOf"), list):
        return " | ".join(ts_type(v, prefix) for v in schema["anyOf"])
    return "unknown"


def main() -> int:
    sys.path.insert(0, str(ROOT / "apps" / "api"))
    from fastapi.testclient import TestClient  # noqa: E402

    from nexus.main import app  # noqa: E402

    spec = TestClient(app).get("/openapi.json").json()
    schemas = spec.get("components", {}).get("schemas", {})
    lines = [
        "/* Auto-generated by apps/api/scripts/gen_types.py - do not edit. */",
        "",
    ]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object" or "properties" in schema or "enum" in schema:
            if "enum" in schema and schema.get("type") == "string":
                lines.append(f"export type {name} = {ts_type(schema)};")
            else:
                lines.append(f"export interface {name} {ts_type(schema)}")
            lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(schemas)} schemas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
